name: Trigger Render Deploy

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes

jobs:
  ping-render:
    runs-on: ubuntu-latest    
    steps:
      - name: Call Render Deploy Hook
        run: |
          curl https://learn-coding-with-copilotkit.onrender.com/copilotkit
          curl https://learn-coding-with-copilotkit-1.onrender.com/copilotkit